#profile-title: VPN
#profile-update-interval: 12
#subscription-userinfo: expire=5774966400; total=0 used=0
#profile-web-page-url: siska.popka.ru
#announce: отсоси админу за впн

vless://59323d7e-a9ee-4cd3-b0b4-6619aeb439c4@85.192.40.221:30634?type=tcp&headerType=none&security=reality&fp=chrome&sni=aws.amazon.com&pbk=jj_fF55rorktfDliBV7oEyP7sS7jSoPJqTnx-AWA1BU&sid=8a8043fa77&spx=/#%F0%9F%87%B3%F0%9F%87%B1%D0%9A%D0%BB%D1%8E%D1%87%20%D0%BE%D1%82%20#🇳🇱Нидерланды
